before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - <<: &build_defaults
      ldflags:
        - -s -w
        - -X "github.com/dutchcoders/spring4shell-scanner/build.BuildDate={{.Date}}"
        - -X "github.com/dutchcoders/spring4shell-scanner/build.CommitID={{.Commit}}"
        - -X "github.com/dutchcoders/spring4shell-scanner/build.ShortCommitID={{.ShortCommit}}"
        - -X "github.com/dutchcoders/spring4shell-scanner/build.GoVersion={{.Env.GOVERSION}}"

    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [amd64, arm64]
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64, arm64]
  - <<: *build_defaults
    id: generate-usage
    goos: [linux]
    goarch: [amd64]
archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
      files:
        - none*
    wrap_in_directory: false
    format: tar.gz
  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip
